export const REGISTER = "REGISTER";
export const REGISTER_COMPLETE = "REGISTER_COMPLETE";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const LOGIN = "LOGIN";
export const LOGIN_COMPLETE = "LOGIN_COMPLETE";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const LOGOUT = "LOGOUT";

export const RESET_ERRORS = "RESET_ERRORS";

export const CREATE_FORUM = "CREATE_FORUM";
export const CREATE_FORUM_COMPLETE = "CREATE_FORUM_COMPLETE";
export const CREATE_FORUM_ERROR = "CREATE_FORUM_ERROR";

export const GET_ALL_FORUMS = "GET_ALL_FORUMS";
export const GET_ALL_FORUMS_COMPLETE = "GET_ALL_FORUMS_COMPLETE";
export const GET_ALL_FORUMS_ERROR = "GET_ALL_FORUMS_ERROR";

export const DELETE_FORUM = "DELETE_FORUM";
export const DELETE_FORUM_COMPLETE = "DELETE_FORUM_COMPLETE";
export const DELETE_FORUM_ERROR = "DELETE_FORUM_ERROR";

export const GET_FORUM_DISCUSSONS = "GET_FORUM_DISCUSSONS";
export const GET_FORUM_DISCUSSONS_COMPLETE = "GET_FORUM_DISCUSSONS_COMPLETE";
export const GET_FORUM_DISCUSSONS_ERROR = "GET_FORUM_DISCUSSONS_ERROR";

export const CREATE_DISCUSSON = "CREATE_DISCUSSON";
export const CREATE_DISCUSSON_COMPLETE = "CREATE_DISCUSSON_COMPLETE";
export const CREATE_DISCUSSON_ERROR = "CREATE_DISCUSSON_ERROR";
